defaults: &defaults
  adapter: postgresql
  encoding: unicode
  reconnect: false
  host: localhost
  pool: 60

development:
  <<: *defaults
  database: todo_development

test:
  <<: *defaults
  database: todo_test
